
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwvfgmahnnhfxjzmbos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod3ZmZ21haG5uaGZ4anptYm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTU4MDAsImV4cCI6MjA2MTg5MTgwMH0.-t8wZ1VZYqBrwMer7WDkCgKJ08a_6qlv7UCMBxKWxVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

